controllerManager:
  manager:
    env:
      awsSharedCredentialsFile: /home/.aws/credentials
    image:
      repository: registry.k8s.io/cluster-api-aws/cluster-api-aws-controller
      tag: v2.0.2
  replicas: 1
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP

providerArgs:
  awsControllerIAM: 
    role: somerole
    arn: somearn
  eks: true
  eksEnableIAM: false
  EKSAllowAddRoles: false
  EKSFargate: false
  machinePool: false
  eventBridgeInstanceState: false
  autoControllerIdentityCreator: true
  bootstrapFormatIgnition: false
  externalResourceGC: false
  capaLogLevel: 0